baseURL = 'https://comocamp.org/'
languageCode = 'en-us'
title = 'ComoCamp 2027'

enableInlineShortcodes = true
enableRobotsTXT = true

extensions = [
  "hardLineBreak", # newlines result in line breaks
]

[menu]
[[menu.main]]
  name = 'What is the ComoCamp?'
  pageRef = 'como'
  weight = 1
[[menu.main]]
  name = 'Our Location'
  pageRef = 'location'
  weight = 4
[[menu.main]]
  name = 'Our Program'
  pageRef = 'program'
  weight = 5
[[menu.main]]
  name = 'Our Sponsors'
  pageRef = 'supporters'
  weight = 6
[[menu.main]]
name = 'This was our camp 2026!'
pageRef = 'program-hands-on-intro-day'
weight = 7
[[menu.main]]
  name = 'Tickets 2027'
  pageRef = 'participation'
  weight = 8

[Params]
	DateForm = "2006-01-02"
  SaveTheDate = false
  Sections = ["hero", "como", "camp", "community", "bring-your-topics", "location", "program", "program-hands-on-intro-day", "program-open-space", "participation", "faqs", "supporters", "supporters-2", "media-partners", "team", "we-are-looking-forward"]
